### ISSUE TITLE
Problem with height, width, length

### ISSUE THREAD

**Issue by dnikolenkosmartgamma** [latuconsinafr/3d-bin-packager#2]
Hi, if you run this code, you will get  : 
 
 "your-first-bin-identifier": {
            "id": "your-first-bin-identifier",
            "length": 2.22,
            "breadth": 20,
            "height": 5.4,
            "volume": 239.76,
            "weight": 100,
            "fittedItems": [
                {
                    "id": "item-id-3",
                    "length": 2,
                    "breadth": 2,
                    "height": 5,
                    "volume": 20,
                    "weight": 2.53,
                    "rotationType": 0,
                    "position": {
                        "x-axis": 0,
                        "y-axis": 0,
                        "z-axis": 0
                    }
                },
                {
                    "id": "item-id-5",
                    "length": 3.55,
                    "breadth": 2,
                    
 COde :
 ```
$packager = new Packager(2, SortType::DESCENDING);
        $packager->addBin(new Bin('your-bin-identifier', 4, 4.5, 5.221, 50));
        $packager->addBins([
            new Bin('your-first-bin-identifier', 2.22, 5.4, 20, 100),
            new Bin('your-second-bin-identifier', 1, 2, 1.5, 10)
        ]);
        $packager->addItems([
            new Item('item-id-2', 1, 4.225, 2, 5),
            new Item('item-id-3', 2, 5, 2, 2.525),
            new Item('item-id-4', 1, 3.5, 3, 10),
            new Item('item-id-5', 3.551, 2, 2, 12.5)
        ]);

        $packager->withFirstFit()->pack();

        return $this->response($packager->getBins());
```
        
       So length of bin less than sum of items (((
       It can not be packed. Can you tell me if I do something wrong

**Comment by latuconsinafr** [comment]
I've run your code and there's nothing wrong with the result, would you please elaborate on what kind of result you expected?

And I'm sorry can you make it clear what does this mean:

> So length of bin less than sum of items (((
> It can not be packed. Can you tell me if I do something wrong

**Comment by latuconsinafr** [comment]
Found if it's the issue opener mistake, closed.
